# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sampleSizeLE = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sampleSizeLE.setObjectName("sampleSizeLE")
        self.horizontalLayout.addWidget(self.sampleSizeLE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.windowStepLE = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.windowStepLE.setObjectName("windowStepLE")
        self.horizontalLayout_2.addWidget(self.windowStepLE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.distrStepLE = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.distrStepLE.setObjectName("distrStepLE")
        self.horizontalLayout_3.addWidget(self.distrStepLE)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.distrTypeComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.distrTypeComboBox.setObjectName("distrTypeComboBox")
        self.distrTypeComboBox.addItem("")
        self.distrTypeComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.distrTypeComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plotDir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plotDir.setObjectName("plotDir")
        self.horizontalLayout_4.addWidget(self.plotDir)
        self.choosePlotDir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.choosePlotDir.setObjectName("choosePlotDir")
        self.horizontalLayout_4.addWidget(self.choosePlotDir)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.buildButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buildButton.setObjectName("buildButton")
        self.horizontalLayout_8.addWidget(self.buildButton)
        self.showPlots = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.showPlots.setObjectName("showPlots")
        self.horizontalLayout_8.addWidget(self.showPlots)
        self.plotsAreBuiltLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.plotsAreBuiltLabel.setObjectName("plotsAreBuiltLabel")
        self.horizontalLayout_8.addWidget(self.plotsAreBuiltLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.energyParamSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.energyParamSave.setObjectName("energyParamSave")
        self.horizontalLayout_9.addWidget(self.energyParamSave)
        self.statParamSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.statParamSave.setObjectName("statParamSave")
        self.horizontalLayout_9.addWidget(self.statParamSave)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loadedFileTxt = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.loadedFileTxt.setObjectName("loadedFileTxt")
        self.horizontalLayout_6.addWidget(self.loadedFileTxt)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.energyParamSaved = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.energyParamSaved.setEnabled(True)
        self.energyParamSaved.setObjectName("energyParamSaved")
        self.horizontalLayout_7.addWidget(self.energyParamSaved)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.statsParamSaved = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.statsParamSaved.setObjectName("statsParamSaved")
        self.horizontalLayout_10.addWidget(self.statsParamSaved)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(False)
        self.actionSave.setObjectName("actionSave")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Обработка данных АЭ"))
        self.label.setText(_translate("MainWindow", "Введите размер выборок:"))
        self.label_3.setText(_translate("MainWindow", "Введите шаг смещения окна:"))
        self.label_2.setText(_translate("MainWindow", "Введите шаг по координате:"))
        self.label_4.setText(_translate("MainWindow", "Выберите тип аппроксимации:"))
        self.distrTypeComboBox.setCurrentText(_translate("MainWindow", "Гаусс"))
        self.distrTypeComboBox.setItemText(0, _translate("MainWindow", "Гаусс"))
        self.distrTypeComboBox.setItemText(1, _translate("MainWindow", "Лоренц"))
        self.plotDir.setText(_translate("MainWindow", "Выбрать директорий для графиков"))
        self.choosePlotDir.setText(_translate("MainWindow", "Директорий не выбран"))
        self.buildButton.setText(_translate("MainWindow", "Построить гистограмму и аппроксимацию"))
        self.showPlots.setText(_translate("MainWindow", "Показывать графики"))
        self.plotsAreBuiltLabel.setText(_translate("MainWindow", "Графики построены!"))
        self.energyParamSave.setText(_translate("MainWindow", "Сохранить энергетические данные"))
        self.statParamSave.setText(_translate("MainWindow", "Сохранить статистические данные"))
        self.loadedFileTxt.setText(_translate("MainWindow", "Файл не загружен"))
        self.energyParamSaved.setText(_translate("MainWindow", "Энергетические параметры распределений сохранены!"))
        self.statsParamSaved.setText(_translate("MainWindow", "Статистические параметры распределений сохранены!"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить как"))


